// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CalculatePrice provides a mock function with given fields: typeArg, margin, exchangeRate
func (_m *Service) CalculatePrice(typeArg string, margin float64, exchangeRate float64) (float64, error) {
	ret := _m.Called(typeArg, margin, exchangeRate)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string, float64, float64) float64); ok {
		r0 = rf(typeArg, margin, exchangeRate)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, float64, float64) error); ok {
		r1 = rf(typeArg, margin, exchangeRate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
